!!com.example.app.properties.PropertiesData
appiumProperties:
  platformName: android
  deviceName: device
  udid: ac9268200405
  app: /home/fattah/Downloads/Programs/Compressed/app-debug_v.1.0.apk
  automationName: UIAutomator2
  newCommandTimeout: 120
  autoGrantPermissions: true
